name: Publish XXXX in npm

on:
    push:
        tags:
            - '*'

jobs:
    build-app:
        env:
            CI: true

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x, 17.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: 'https://registry.npmjs.org'
            - run: npm ci
            - run: npm run build --if-present
            - run: npm run lint
            # - run: npm run test-ci
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM }}
